config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get  '/hark',     to: 'pages#hark'
  get 'harks/:name', to: 'posts#index'

  get  '/raven',    to: 'pages#about'
  get  '/contact',  to: 'pages#contact'

  get 'password_resets/new'
  get 'password_resets/edit'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts, shallow: true do
  	resources :comments, only: [:create, :destroy]
  end
end

app/views/pages/about.html.erb
<%= render 'layouts/navigation' %>

<% provide(:title, "Raven") %>


<div class="container">
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr class="tagline-divider">
                <h2 class="intro-text text-center">What is
                    <strong>The Raven Circle?</strong>
                </h2>
                <hr class="tagline-divider">
                <br>
                <br>
            </div>
            <div class="col-md-12">
              <p>The circle is all that encompasses the world fully and completely.</p>
              <p>When joining The Raven circle, one can discover a new world of magic, wisdom and insight.</p>
              <p>Raven G Waters, a founder of "sisters of spirit" (SOS) will reveal her world on many topics, leading with love, compassion, understanding and humor.</p>
              <p>Welcome to the Raven circle.</p>
          </div>
            <br>

            <div class="clearfix"></div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr class="tagline-divider">
                <h2 class="intro-text text-center">My Story:
                    <strong>Finding My Wings</strong>
                </h2>
                <hr class="tagline-divider">
                <br>
                <br>
            </div>
            <div class="col-md-6">
                <%= link_to image_tag("raven-profile.jpg") %>
            </div>
            <br>
            <div class="col-md-6" id="about">
                <p>No life has clean beginnings. I was lost. The life I thought was wrapping up. My <i>"happily ever after"</i> was a false truth. This is when I first began to discover my wings.</p>
                <p>From the ashes, like a Pheonix, I began to create my <i>"happily ever after"</i>, every day! I thought I had figured out all there was <i>within</i>, but truth be told I had yet to open many doors.
                <p>I found the experiences of my past had new light and meaning. The many dots of my life were now being connected. I went from a mindset where I felt removed from time and space, to wielding it.</p>
                <p>This journey is when my wings took flight. I will forever be thankful to the events that helped propel my transformation into motion. Even though at the time those moments may not have been seen as the gift, they were. I am truly grateful for them, and the opportunity to share my life with you.</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr class="tagline-divider">
                <h2 class="intro-text text-center">My
                    <strong>Specialties</strong>
                </h2>
                <hr class="tagline-divider">
            </div>
            <div class="col-sm-3 text-center">
              <div class="singlecard">
                  <div id="card1" class="card">
                    <figure class="front"><%=image_tag("starchild-tarot.jpg")%></figure>
                    <figure class="back"><%=image_tag("tarot.jpg")%>
                      <div class="description">
                        <p class="brand-before">Always conducted with positive intentions. Here you will discover where your path is headed and how to change direction if needed. All messages come to best serve you in your direction with work, home, and everyday life. Is your yesterday holding you back from today, or tomorrow?</p>
                      </div>
                    </figure>
                  </div>
                </div>
                <h2 class="intro-text text-center">
                  <strong>Tarot</strong>
                </h2>
            </div>
            <div class="col-sm-3 text-center">
              <div class="singlecard">
                  <div id="card1" class="card">
                    <figure class="front"><%=image_tag("starchild-tarot.jpg")%></figure>
                    <figure class="back"><%=image_tag("pendulum.JPG")%>
                      <div class="description">
                        <p class="brand-before">Filled with questions? The pendulum has answers! Using the energy and our collective consciousness watch the pendulum dance to your yes or no questions. Please know that not all answers will be revealed until the time is right. Will the pendulum answer some of the burning questions that plague your mind? The answer could be yes!</p>
                      </div>
                    </figure>
                  </div>
                </div>
                <h2 class="intro-text text-center">
                  <strong>Pendulum</strong>
                </h2>
            </div>
            <div class="col-sm-3 text-center">
                <div class="singlecard">
                    <div id="card1" class="card">
                      <figure class="front"><%=image_tag("starchild-tarot.jpg")%></figure>
                      <figure class="back"><%=image_tag("reiki.jpeg")%>
                        <div class="description">
                          <p class="brand-before">If you have ever experienced a pain that just won't go away, Reiki is the option for you. You may carry stress in your shoulders, or tiredness behind your eyes. Our bodies hold a lot within. With the art of Reiki, we begin to better understand that our world runs on the energy we put out and take in. Experience tranquility with Reiki.</p>
                        </div>
                      </figure>
                    </div>
                </div>
                <h2 class="intro-text text-center">
                  <strong>Reiki</strong>
                </h2>
            </div>
            <div class="col-sm-3 text-center">
              <div class="singlecard">
                  <div id="card1" class="card">
                    <figure class="front"><%=image_tag("starchild-tarot.jpg")%></figure>
                    <figure class="back"><%=image_tag("spiritual-counseling.jpg")%>
                      <div class="description">
                        <p class="brand-before">Life is a spiritual journey. I am a reverend with a wonderful and distinct insight on the path of spiritual growth. I have been blessed by Amma (Mata Amritanandamayi) Sri Karunamayi. I am willing and able to help you with your own spiritual growth in whatever form it may be.</p>
                      </div>
                    </figure>
                  </div>
                </div>
                <h2 class="intro-text text-center">
                  <strong>Spiritual Counseling</strong>
                </h2>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- /.container -->

<!-- Tarot Cards -->
<script>
$(function() {
  $('.card').click( function( event ) {
    $( event.currentTarget ).toggleClass('flipped');
  });
});
</script>

app/views/pages/contact.html.erb
<%= render 'layouts/navigation' %>

<% provide(:title, "Take Flight") %>

<div class="container">
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr class="tagline-divider">
                <h2 class="intro-text text-center">Birds of a feather
                    <strong>flock together!</strong>
                </h2>
                <hr class="tagline-divider">
                <br>
                <h2 class="brand-before"><b>Guided Meditations</b></h2>

                <p class="brand-before">Many studies have shown the positive power of meditation heightens awareness and wellbeing amoung many other things. Guided meditation allows your mind to focus on the words being said until they float away. We respect that meditation is different for all people and welcome you to meditate with us.</p>

                <p class="brand-before">Thursdays (first, second, and last of each month)</p>
                <p class="brand-before">To learn more please contact: </p>
                <p><%= link_to 'oursistersofspirit@aol.com', 'mailto:oursistersofspirit@aol.com', class: 'custom-link' %></p>




                <br>
                <hr class="tagline-divider">
                <br>
                <h2 class="brand-before"><b>The Witching Hour</b></h2>

                <p class="brand-before">With open minds we discuss our understanding of all energy and the purpose of working with tools for spells among other questions to be answered too! One thing is for certain, witches are very real, and magic is all around us! It wouldn't be <i>the witching hour</i> if we didn't end in a spell! Will it bring wealth into your life, protection from negativity, find out at the witching hour!</p><br>

                <p class="brand-before">Third Thursday of each month</p>
                <p class="brand-before">To learn more please contact: </p>
                <p><%= link_to 'oursistersofspirit@aol.com', 'mailto:oursistersofspirit@aol.com', class: 'custom-link' %></p>
                <br>
                <hr class="tagline-divider">
                <br>
                <h2 class="brand-before"><b>Raven's Ramblings</b></h2>

                <p class="brand-before">As the flock grows, Raven will be conducting classes offered to her circle. We will discuss topics based off of your insight and suggestions. And of course, there is always the opportunity to simply chat and get to know Raven more!</p><br>

                <p class="brand-before">TBA</p>
                <br>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr class="tagline-divider">
                <h2 class="intro-text text-center">Contact
                    <strong>Raven</strong>
                </h2>
                <hr class="tagline-divider">
                <br>
                <br>
            </div>

            <div class="col-md-6">
                <p>If you have any direct questions, insights or suggestions please contact me by clicking on the gmail icon below. All thoughts and wishes are important so please feel free to contact me at any time.</p><br>
                <p>Raven will try to answer all messages promptly, however depending on volume of said messages response time may vary. If there is something you would like to see on this site, please state that too! The Raven circle, like Raven's world is always changing and improving for the better!</p><br>
                <p>For information about <strong>readings</strong> please contact:</p>
                <p><%= link_to 'oursistersofspirit@aol.com', 'mailto:oursistersofspirit@aol.com', class: 'custom-link' %></p><br>
                <p>If you wish to see Raven directly, please put Raven in the subject line along with the service your looking for.</p>
                <p>Thank you for being a part of <strong>The Raven Circle!</strong></p>
            </div>

            <div class="col-md-6">
                <%= image_tag("my-cards.jpg")%><br>
                <% if current_user.try(:admin?) %>
                  <br>
                  <%= link_to 'View Users', users_path, class: 'button center' %>
                <% end %>
            </div>
            <br>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- /.container -->

app/views/pages/hark.html.erb
<%= render 'layouts/navigation' %>

<% provide(:title, "Hark The Raven") %>

<div class="container">
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <br>
                <hr class="tagline-divider">
                <h2 class="intro-text text-center">Hark
                    <strong>The Raven</strong>
                </h2>
                <hr class="tagline-divider">
                <br>
                <br>
            </div>

            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                              <%= image_tag("carousel/deep-waters.jpg") %><br>
                              <div class="brand-name">Deep Waters</div>
                              <hr class="tagline-divider">
                              <h2 class="brand-before">
                                  <small>Depth within the water, explains the insight and Depth of Raven.</small>
                              </h2>
                              <h2 class="brand-before">
                                  <small>
                                    If you are looking to read something to help change your perspective on your world or what it means to be living in this time and place these posts are for you.
                                </small>
                              </h2>
                            </div>
                            <div class="item">
                              <%= image_tag("carousel/moments-in-motion.jpg") %><br>
                              <div class="brand-name">Moments In Motion</div>
                              <hr class="tagline-divider">
                              <h2 class="brand-before">
                                  <small>Moments in motion means to connect the mind, body and spirit.</small>
                              </h2>
                              <h2 class="brand-before">
                                  <small>
                                    Here Raven will share her experiences on her journey towards a healthier balanced life style. Humor matched with insight, these posts are a wonderful read to lift the spirit and stay grounded.
                                  </small>
                              </h2>
                            </div>
                            <div class="item">
                              <%= image_tag("carousel/underlying-developments.jpg") %><br>
                              <div class="brand-name">Underlying Developments</div>
                              <hr class="tagline-divider">
                              <h2 class="brand-before">
                                  <small>Underlying Developments deals with all subjects and that which lies beyond.</small>
                              </h2>
                              <h2 class="brand-before">
                                  <small>
                                    The essence that drives all things. The something, or the nothing at all. These posts are here to help direct one to their own understanding.
                                </small>
                              </h2>
                            </div>
                            <div class="item">
                              <%= image_tag("carousel/seeds-of-change.jpg") %><br>
                              <div class="brand-name">Seeds Of Change</div>
                              <hr class="tagline-divider">
                              <h2 class="brand-before">
                                  <small>Our world is a precious gift. Forever changing and growing.</small>
                              </h2>
                              <h2 class="brand-before">
                                  <small>
                                      Seeds Of Change are the thoughts and actions that lead one to be a natural healer in our world. Are you ready for a change?.
                                </small>
                              </h2>
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="box">
                <div class="col-lg-12 text-left">
                  <p class="text-center">
                          Click on the tags below to navigate to a list of posts regarding the following topics:
                  </p>
                  <% @tags = Tag.all.order('created_at DESC') %>
                  <p>
                    <% @tags.each do |tag| %>
                        #<%= link_to tag.name, "/harks/#{tag.name}" %>
                    <% end %>
                  </p>
                </div>
            </div>
            <% if current_user.try(:admin?) %>
              <%= link_to 'Create Post', new_post_path, class: 'button center' %>
            <% end %>
            <br>
        </div>
    </div>
</div>
<!-- /.container -->

<!-- Carousel -->
<script>
  $('.carousel').carousel({
      interval: 5000 //changes the speed
  });
</script>

app/views/pages/home.html.erb
<%= render 'layouts/navigation' %>

    <!-- Crystal Ball -->
    <div class="crystal-ball-container text-center img-responsive">
        <div class="crystal-ball img-responsive"></div>
        <div id="text"></div>
        <div id="author"></div>
    </div>

    <div class="button" id="new-vision">New Vision</div><br>

<%= javascript_include_tag "home", "data-turbolinks-track" => true  %>